// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface SibyllaConfig {
    id:                         string;
    knowledgeFilter:            KnowledgeFilter;
    title:                      string;
    memoryConfiguration:        MemoryConfiguration;
    baseSystemPrompt:           string;
    baseAssistantPrompt:        string;
    maxTokens:                  number;
    model:                      string;
    temperature:                number;
    topP:                       number;
    frequencyPenalty:           number;
    presencePenalty:            number;
    functionsDefaultAnswerHook: null;
    functionsBeforeAnswerHook:  null;
    sibyllaName:                string;
    hidden:                     boolean | null;
}

export interface KnowledgeFilter {
}

export interface MemoryConfiguration {
    factMemoryTTL:            number;
    memorySpan:               number;
    chatMemoryMaxContextPerc: number;
    contextTokens:            number;
    factFilter:               null;
    limit:                    number;
    categoryFilter:           string[] | null;
    tagFilter:                string[];
    autoCutPercentage:        number;
}
