import { retry } from 'rxjs';

const language = {
  defaultBaseAssistantPrompt: 'Ciao, come posso aiutarti?',
  thanksFeedback: 'Grazie per il tuo feedback!',
  thanks: 'Grazie!',
  welcome: 'Ciao!',
  enter: 'Invia',
  welcomeToSibylla:
    'Sono Sibylla, la tua assistente virtuale per orientarti nella conoscenza.',
  welcomeEnter: 'Entra in Sibylla',
  selection: 'Scegli la Sibylla',
  newchatconfirm:
    'Creando una nuova chat, verrà eliminata la conversazione corrente. Sei sicuro di voler continuare?',
  selectionEnter: 'Entra',
  newchat: 'Stai iniziando una nuova conversazione con Sibylla',
  chat: 'Chat',
  explain: 'Explain',
  confirm: 'Conferma',
  knowledge: 'Knowledge',
  newChat: 'Nuova Chat',
  add: 'Aggiungi',
  addSource: 'Aggiungi fonte',
  sibyllaBackoffice: 'Sibylla Backoffice',
  askQuestion: 'Fai una domanda',
  usedForAnswering: 'utilizzati per la risposta',
  retrieved: 'recuperati',
  source: 'Fonte',
  category: 'Categoria',
  type: 'Tipo',
  wantToLeaveAComment: 'Vuoi lasciare un commento?',
  max300Characters: 'Massimo 300 caratteri',
  cancel: 'Annulla',
  writeAContent: 'Modifica la fonte',
  title: 'Titolo',
  titleIsRequired: 'Title richiesto',
  titleMaxlength: 'Titolo troppo lungo',
  titleMinlength: 'Titolo troppo corto',
  text: 'Inserisci testo',
  textRequired: 'Contenuto richiesto',
  textMaxlength: 'Contenuto troppo lungo',
  textMinlength: 'Contenuto troppo corto',
  content: 'Contenuto',
  contentIsRequired: 'Contenuto richiesto',
  contentMin10Characters: 'Il contenuto deve essere lungo almeno 10 caratteri.',
  delete: 'Elimina',
  close: 'Chiudi',
  edit: 'Modifica',
  expiration: 'Scadenza',
  tag: 'Tag',
  searchOnKnowledgebase: 'Esegui una ricerca sulla base di conoscenza',
  selectResultToShowDetails:
    'Seleziona un risultato per visualizzarne il dettaglio',
  loadCsvInstructions:
    'Carica un CSV senza intestazioni con una prima colonna di domande e una seconda colonna con le corrispondenti risposte attese',
  successfullyUploaded: 'correttamente caricato',
  youCanCloseTheWindow: 'Puoi chiudere la finestra',
  evaluationQuestions: 'Domande di valutazione',
  search: 'Cerca',
  optional: 'Opzionale',
  resultsFound: 'risultati trovati',
  importDocument: 'Importa un documento',
  document: 'Documento',
  loadDocument: 'Carica documento',
  url: 'Url',
  requestSuccess: 'Richiesta di acquisizione inviata con successo',
  requestErr: 'Errore nella richiesta di acquisizione',
  file: 'File',
  loadfile: 'Carica file',
  loadlink: 'Inserisci link',
  loadText: 'Scrivi Contenuto',
  typeOfFile: 'Formati accettati: .pdf, .docx, audio (.mp3), video (.mp4)',
  loadfileText: 'Trascina il file per caricarlo',
  invalidLink: 'Link non valido',
  Uploadsuccessful: 'Caricato con successo!',
  WarningDataIsmissing: 'Attenzione! Nessuna fonte caricata',
  unsupportedformat: 'Formato del file non supportato',
  Errorreadingfile: 'Errore nella lettura del file',
  SearchSibylla: 'Cerca in Sibylla...',
  SourcesUsed: 'Fonti utilizzate per la risposta',
  ViewSourcesUnused: 'Vedi altre fonti recuperate',
  RelevantSources: 'Fonti rilevanti',
  OtherRetrivedSources: 'Altre fonti recuperate',
  send: 'Invio',
  errorRetry: 'Si è verificato un errore imprevisto',
  retry: 'Riprova',
  askSibylla: 'Chiedi a Sibylla',
};

export default language;
