const language = {

  defaultBaseAssistantPrompt: "Ciao, come posso aiutarti?",
  thanksFeedback: "Grazie per il tuo feedback!",
  thanks: "Grazie!",
  enter: "Entra",
  chat: "Chat",
  explain: "Explain",
  knowledge: "Knowledge",
  newChat: "Nuova Chat",
  add: "Aggiungi",
  sibyllaBackoffice: "Sibylla Backoffice",
  askQuestion: "Fai una domanda",
  usedForAnswering: "utilizzati per la risposta",
  retrieved: "recuperati",
  source: "Fonte",
  category: "Categoria",
  type: "Tipo",
  wantToLeaveAComment: "Vuoi lasciare un commento?",
  max300Characters: "Massimo 300 caratteri",
  cancel: "Annulla",
  writeAContent: "Scrivi un contenuto",
  title: "Titolo",
  titleIsRequired: "Title is required.",
  content: "Contenuto",
  contentIsRequired: "Content is required.",
  contentMin10Characters: "Il contenuto deve essere lungo almeno 10 caratteri.",
  delete: "Elimina",
  close: "Chiudi",
  edit: "Modifica",
  expiration: "Scadenza",
  tag: "Tag",
  searchOnKnowledgebase: "Esegui una ricerca sulla base di conoscenza",
  selectResultToShowDetails: "Seleziona un risultato per visualizzarne il dettaglio",
  loadCsvInstructions: "Carica un CSV senza intestazioni con una prima colonna di domande e una seconda colonna con le corrispondenti risposte attese",
  successfullyUploaded: "correttamente caricato",
  youCanCloseTheWindow: "Puoi chiudere la finestra",
  evaluationQuestions: "Domande di valutazione",
  search: "Cerca",
  optional: "Opzionale",
  resultsFound: "risultati trovati",
}

export default language;